### PR TITLE
UPDATE: enable checkUninitializedProperties

### PR DESCRIPTION
**Pull request by mantebalzaraviciute**
Issue: https://github.com/JumpTwentyFour/php-coding-standards/issues/26 

### Enabled uninitialised properties check in stan

Docs for reference: https://phpstan.org/config-reference#checkuninitializedproperties 😇

### CODE REVIEW

**Review by mmorganJ24 — APPROVED** [review]

**Comment by AlexJump24** [comment]
My only concern with adding this to the base is for any existing projects that fall foul of this rule, can we disable it? If we can then it seems like a sensible addition, if not it might make more sense to do it at a project level.

**Comment by mantebalzaraviciute** [comment]
@AlexJump24 I think we can disable it by adding the same but as false, i think it would override it? Also i ran this on LMR and it was only 3 issues, so i think we can fix those :)

**Comment by AlexJump24** [comment]
> @AlexJump24 I think we can disable it by adding the same but as false, i think it would override it? Also i ran this on LMR and it was only 3 issues, so i think we can fix those :)

Could we test this, just concerned some bigger and less compliant projects would lead us to having to baseline a lot of issues.

**Comment by mantebalzaraviciute** [comment]
> > @AlexJump24 I think we can disable it by adding the same but as false, i think it would override it? Also i ran this on LMR and it was only 3 issues, so i think we can fix those :)
> 
> Could we test this, just concerned some bigger and less compliant projects would lead us to having to baseline a lot of issues.

It works! If we disable it by project it gets overriden and the issues are ignored :)

**Review by AlexJump24 — APPROVED** [review]

**Review by AlexJump24 — APPROVED** [review]

**Pull request merged**
